const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{night: 0},
	{day: 0},
	{Health: 0},
	{ScrollTo: 0},
	{Jumpthru: 0},
	{Platform: 0},
	{CHICK: 0},
	{Solid: 0},
	{plataform: 0},
	{Keyboard: 0},
	{move: 0},
	{imbisible_wall: 0},
	{enemy_tank: 0},
	{Audio: 0},
	{Bullet: 0},
	{bullet: 0},
	{coin: 0},
	{Rotate: 0},
	{trap1: 0},
	{bullet_test: 0},
	{Particles: 0},
	{score: 0},
	{score_number: 0},
	{gift: 0},
	{"2ndLayoutPlatform": 0},
	{Score: 0}
];

self.InstanceType = {
	night: class extends self.ISpriteInstance {},
	day: class extends self.ISpriteInstance {},
	CHICK: class extends self.ISpriteInstance {},
	plataform: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	imbisible_wall: class extends self.ISpriteInstance {},
	enemy_tank: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	bullet: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	trap1: class extends self.ISpriteInstance {},
	bullet_test: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	score: class extends self.ITextInstance {},
	score_number: class extends self.ITextInstance {},
	gift: class extends self.ISpriteInstance {},
	_2ndLayoutPlatform: class extends self.ISpriteInstance {}
}